<?php
require 'Views/template/adminHeader.phtml';
?>
<!-- Page Content  -->
<div id="content">








    <div class="header body-background3">
        <div class="d-flex justify-content-between">
            <div class="p-2 align-self-center">
                <button type="button" id="sidebarCollapse" class="sidebutton-hover sidebutton">
                    <i class="fa fa-align-left"></i>
                    <span>Menu</span>
                </button>
            </div>
            <div class="p-2 align-self-center">
                <a class="dashboard">Admin Panel</a>
            </div>
            <div class="p-2 align-self-center">
            </div>
        </div>
    </div>

    <div class="body-background">
        <div class="container-fluid d-flex justify-content-center align-items-center h-100">
            <div class="card cardBackgroud p-3 text-center py-4">
                <img src="images/pngegg3.png" width="460" height="345">
                <h4 class="card-title">Create Experiment</h4>
                <form method="post" action="" enctype="multipart/form-data">
                    <p>Select the type of experiment:</p>
                    <div class="row justify-content-center mt-4 ml-2 mr-1">
                        <div class="col col-md-auto">
                            <a href="createSurveys.php"><button type="submit" name="surveyBtn" class="bn632-hover bn28">Surveys</button></a>
                            <a href="createPolls.php"><button type="submit" name="pollBtn" class="bn631-hover bn28">Polls</button></a>
                        </div>
                        <div class="col col-md-auto">
                            <a href="createPrototypes.php"><button type="submit" name="prototypeBtn" class="bn630-hover bn28">Prototypes</button></a>
                            <a href="createDiscussions.php"><button type="submit" name="dicussionBtn" class="bn633-hover bn28">Discussions</button></a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    <!-- jQuery CDN - Slim version (=without AJAX) -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <!-- Popper.JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>



    <script type="text/javascript">
        $(document).ready(function() {

            $('#sidebarCollapse').on('click', function() {

                $('#sidebar').toggleClass('active');

            });

        });
    </script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            const rows = document.querySelectorAll("tr[data-href]");

            rows.forEach(row => {
                row.addEventListener("click", () => {
                    window.location.href = row.dataset.href;
                });
            });
        });
    </script>
    </body>

    </html>