<?php
require 'Views/template/adminHeader.phtml';
?>
<!-- Page Content  -->
<div id="content">








    <div class="header body-background3">
        <div class="d-flex justify-content-between">
            <div class="p-2 align-self-center">
                <button type="button" id="sidebarCollapse" class="sidebutton-hover sidebutton">
                    <i class="fa fa-align-left"></i>
                    <span>Menu</span>
                </button>
            </div>
            <div class="p-2 align-self-center">
                <a class="dashboard">Admin Panel</a>
            </div>
            <div class="p-2 align-self-center">
            </div>
        </div>
    </div>




    <div class="row ml-3 mr-3">

        <div class="col">
            <div class="dashboard2"> <a><i class="fa fa-area-chart" aria-hidden="true"></i></a> Create Protot</div>
        </div>
    </div>





    <div class="col">

        <div class="container py-4">
            <article class="postcard green3 green">
                <div class="postcard__text ">
                    <h1 class="postcard__title green "><a href="#">Prototypes</a></h1>
                    <div class="postcard__bar"></div>

                    <h4 class="card-title">Create Prototype</h4>
                    <form method="POST" action="">
                        <div class="mt-3 px-3"> <input type="text" name="name" class="form-control" placeholder="Survey Name" required> </div>
                        <div class="mt-3 px-3"> <input type="text" name="totalTime" class="form-control" placeholder="Enter total estimate time" required> </div>
                        <div class="mt-3 px-3"> <input type="text" name="description" class="form-control" placeholder="Enter some description"> </div>
                        <div class="mt-3 px-3"> <input type="text" name="link" class="form-control" placeholder="Enter/Paste Google forms embedded link"> </div>
                        <div class="mt-3 px-3"> <button type="submit" name="createPrototype" class="btn-danger text-uppercase"> <span>Create Survey</span> </button> </div>
                    </form>
                </div>
            </article>
        </div>
    </div>

</div>











<!-- jQuery CDN - Slim version (=without AJAX) -->

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<!-- Popper.JS -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>

<!-- Bootstrap JS -->

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>



<script type="text/javascript">
    $(document).ready(function() {

        $('#sidebarCollapse').on('click', function() {

            $('#sidebar').toggleClass('active');

        });

    });
</script>
<script>
    document.addEventListener("DOMContentLoaded", () => {
        const rows = document.querySelectorAll("tr[data-href]");

        rows.forEach(row => {
            row.addEventListener("click", () => {
                window.location.href = row.dataset.href;
            });
        });
    });
</script>






</div>
</body>

</html>