<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="css/userSignup.css">
    <title>Sign Up</title>
</head>
<body>
<div class="body-background">
<?php
    if($error == 1){
        echo '<div class="alert alert-success alert-dismissible d-flex align-items-center fade show">
                    <i class="bi-exclamation-octagon-fill"></i>
                    <strong class="mx-2">Account is now registered!</strong> <a href="index.php" class="btn-primary p-1">Login Now</a>
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              </div>';
    } 
    elseif($error == 2){ 
        echo '<div class="alert alert-danger alert-dismissible d-flex align-items-center fade show">
                    <i class="bi-exclamation-octagon-fill"></i>
                    <strong class="mx-2">Email is already registered!</strong>Please check spelling!
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
              </div>';
    }
?>
    <div class="container-fluid d-flex justify-content-center align-items-center h-100">
        <div class="card cardBackgroud p-3 text-center py-4">
            <img src="images/pngegg3.png" width="460" height="345">
            <h4 class="card-title">Create account</h4>
            <div> <span class="card-description">Already have an account?</span> <a href="index.php" class="text-warning  text-decoration-none login">Login</a> </div>
            <form method="post" action="../signup.php" enctype="multipart/form-data">
            <div class="mt-3 px-3"> <input type="text" name = "first_name" class="form-control" placeholder="First Name" required> </div>
            <div class="mt-3 px-3"> <input type="text" name = "last_name" class="form-control" placeholder="Last Name" required> </div>
            <div class="mt-3 px-3"> <input type = "text" name = "DoB" onfocus="(this.type='date')" onblur="if(!this.value)this.type='text'" class="form-control" placeholder="DOB" required></div>
            <div class="mt-3 px-3"> <input type="email" name = "email" class="form-control" placeholder="E-mail" required> </div>
            <div class="mt-3 px-3"> <input type="text" name = "gender" class="form-control" placeholder="Gender (Optional)"> </div>
            <div class="mt-3 px-3"> <input type="password" name="pwd" class="form-control" id="signup-Password" placeholder="Password" required> </div>
            <div class="mt-3 px-3"> <button type="submit" name="signupbutton" value="Signup" class="btn-block button2 btn-signup text-uppercase"> <span>Sign up</span> </button> </div>
            </form>
        </div>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>