<!DOCTYPE html>
<html>
<head>    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="css/adminDashboard.css">
    <link rel="stylesheet" href="css/userProfile.css">
    <script src="js/script.js"></script>
    <script src="js/moreJS.js"></script>
    <!--<link rel="stylesheet" href="css/createExperiment.css">-->
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <title>Document</title>
    
    <!-- Font Awesome JS -->
	<script src="https://use.fontawesome.com/e8115dfc1a.js"></script>
</head>
<body class="body-background">


<div class="wrapper ">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
		<img src="images/pngegg3.png" width="460" height="345">
		<div class="text-center bg-primary card mg-auto " style="width: 16rem; color: white;">Admin</div>
            </div>

            <ul class="list-unstyled components text-center">
                <li class="sidebarhov">
                    <a href="adminpanel.php">
						<i class="fa fa-bar-chart" aria-hidden="true"></i> Home</a>
                </li>
				<li class="sidebarhov">
                    <a href="userList.php"> 
						  <i class="fa fa-user" aria-hidden="true"></i> Users</a>
                </li>
				<li class="sidebarhov">
                    <a href="createExperiment.php"><i class="fa fa-cog" aria-hidden="true"></i> Create Experiments</a>
                </li>
            </ul>
			<ul class="list-unstyled components text-center ">
                <li>
                    <a href="logoutAdmin.php" class="sidebarhov" >Log Out</a>
                </li>
            </ul>
        </nav>

        <div id="content">







 